name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            docker_arch: amd64
          - arch: aarch64
            docker_arch: arm64

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install cross
      run: cargo install cross

    - name: Build binary
      run: |
        cd xt
        cross build --release --target ${{ matrix.arch }}-unknown-linux-gnu

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: xt
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/${{ matrix.docker_arch }}
        build-args: |
          TARGETARCH=${{ matrix.docker_arch }}
          RUST_ARCH=${{ matrix.arch }}
        tags: |
          ${{ github.repository_owner}}/${{ github.repository }}:latest
          ${{ github.repository_owner}}/${{ github.repository }}:${{ github.sha }}
