name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            os: linux
            arch: x86_64
            docker_arch: amd64
          - target: aarch64-unknown-linux-gnu
            os: linux
            arch: aarch64
            docker_arch: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0.0.17
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          working-directory: xt
          strip: true

      - name: Package Binary
        run: |
          cd xt/target/${{ matrix.platform.target }}/release
          tar czf xt-${{ matrix.platform.target }}.tar.gz xt
          shasum -a 256 xt-${{ matrix.platform.target }}.tar.gz > xt-${{ matrix.platform.target }}.tar.gz.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: Release ${{ github.ref_name }}
          files: |
            xt/target/${{ matrix.platform.target }}/release/xt-${{ matrix.platform.target }}.tar.gz
            xt/target/${{ matrix.platform.target }}/release/xt-${{ matrix.platform.target }}.tar.gz.sha256

